### ISSUE TITLE
NEXUS-37899: yum proxy repo fails when rpms are on different base url

### ISSUE THREAD

**Issue by amfleurke** [sonatype/nexus-public#147]
You can proxy a yum repo. But when the repodata xml points to a different base url for the rpm files, that base url is removed by Nexus from the repodata, and the download fails.

e.g. for https://aquasecurity.github.io/trivy-repo/  we can add a proxy that maps [https://aquasecurity.github.io/trivy-repo/] to [https://nexus-url/repository/trivy-repo/]. We can use 
```
[trivy]
 name=Trivy repository
baseurl=https://nexus-url/repository/trivy-repo/rpm/releases/$releasever/$basearch/
 gpgcheck=0
enabled=1
```

The repodata [https://aquasecurity.github.io/trivy-repo/rpm/releases/7/x86_64/repodata/repomd.xml] will list the primary lists.
But the lists (e.g. 52e23160ff9262f84dac766497b7dddf98632d05958bf719f06d87461bae2fbd-primary.xml) then will list the RPMs as:
`<location xml:base="https://github.com/aquasecurity/trivy/releases/download/" href="v0.41.0/trivy-0.32.0.el7.x86_64.rpm"/>`
(notice the absolute URL).

When you download the same xml via Nexus, the base= part is gone. It just says `<location href="v0.41.0/trivy-0.32.0.el7.x86_64.rpm"></location>`

This results in a 404 when doing yum install:

> Downloading packages:
> https://nexus-url/repository/trivy-repo/rpm/releases/7/x86_64/v0.41.0/trivy_0.41.0_Linux-64bit.rpm: [Errno 14] HTTPS Error 404 - Not Found
> 

* Do you have a workaround you are using at present?
I can make it work by proxying https://github.com/aquasecurity/trivy/releases/download/ AND https://aquasecurity.github.io/trivy-repo/rpm/releases/7/x86_64  (note that I have to include version and architecture here, to make relative paths match) and use a group repo to combine the two. But this is very ugly.

* What feature or behavior is this required for?
proxying yum repos

* How could we solve this issue? (Not knowing is okay!)
make Nexus proxy the given base urls too

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Nexus OSS 3.53.1-02

* Anything else?
https://issues.sonatype.org/browse/NEXUS-37899 is a duplicate.

**Comment by nblair** [comment]
Thanks for refiling this here; we have selected this for future work and will update back here when completed.

**Comment by nblair** [comment]
We have completed the investigation, and will be closing this as won't fix. The root cause of the issue is that the metadata returned by this specific registry is malformed, and results in broken paths to components, resulting in Nexus Repository being unable to download the files.

More detail from the investigation:

Looking here...
 
https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64/repodata/repomd.xml
 
I see the primary.xml file can be downloaded from:
 
https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64/repodata/d354503dde1285d5e84855979281482a0e8c8293588fea8cb3cb634bbc5b8c0a-primary.xml.gz
 
And it contains:
 
```
<?xml version="1.0" encoding="UTF-8"?><metadata xmlns="http://linux.duke.edu/metadata/common" xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="1">
<package type="rpm">
  <name>trivy</name>
  <arch>x86_64</arch>
  <version ver="0.45.1" rel="1" epoch="0"></version>
  <checksum pkgid="YES" type="sha256">306fdc6041198144de63f23083620e585dd11e971bb738e4a58b710c031c66ab</checksum>
  <summary>A Fast Vulnerability Scanner for Containers</summary>
  <description>A Fast Vulnerability Scanner for Containers</description>
  <packager>Teppei Fukuda <knqyf263@gmail.com></packager>
  <url>https://github.com/aquasecurity</url>
  <time file="1694849705" build="1694849184"></time>
  <size installed="195832683" package="54374772" archive="195832683"></size>
  <location href="v0.45.1/trivy_0.45.1_Linux-64bit.rpm"></location>
  <format>
    <rpm:license>Apache-2.0</rpm:license>
    <rpm:vendor>aquasecurity</rpm:vendor>
    <rpm:group></rpm:group>
    <rpm:buildhost>fv-az413-210</rpm:buildhost>
    <rpm:sourcerpm>trivy-0.45.1-1.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="1176" end="3040"></rpm:header-range>
    <rpm:provides>
      <rpm:entry ver="0.45.1" name="trivy" flags="EQ" rel="1" epoch="0"></rpm:entry>
    </rpm:provides>
    <file>/usr/bin/trivy</file>
  </format>
</package>
</metadata>
```

Note that the "location href" is "v0.45.1/trivy_0.45.1_Linux-64bit.rpm. So combining that with the remote base URL of "https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64" we get:
 
https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64/v0.45.1/trivy_0.45.1_Linux-64bit.rpm
 
But a request for that path relative to the repository's base URL yields a 404.

We suspect the only reason yum works directly with that remote is that the sqllite metadata doesn't have this problem
 
https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64/repodata/81e5d1a887b1c7a26897ffc18dc3f0213daacc025b17139c8a01faf8a0cfebbc-primary.sqlite.bz2

Nexus Repository does not have support for parsing the sqllite metadata.

**Comment by ntavares** [comment]
Hi @nblair you refer to the "remote base URL" of "https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64"?

The XML you've pasted is not accurate, it should read:
```
<location xml:base="https://github.com/aquasecurity/trivy/releases/download/" href="v0.48.0/trivy_0.48.0_Linux-64bit.rpm"/>
```
(fetched just now from file:///home/nmct/Downloads/47e20126e2ea68d51adf0c7aaa2dc906fb6e322423cc3cad63ed71b7912a119b-primary.xml )

.. where there's this attribute xml:base specifying the base, and indeed 

https://github.com/aquasecurity/trivy/releases/download/v0.48.0/trivy_0.48.0_Linux-64bit.rpm

does return a 200. Therefore, it's not a broken repository, but rather an inability of Nexus to follow the unusual construct.

I quickly scanned the web for the RPM XML metadata spec as I've never seen this either before but, assuming it's in the spec, I think it would be a nice addition, and feels like a fairly simple patch. Please could you reopen this issue?

PS: quickly looking at the code of createrepo (an industry standard), it's there (there seems to be a conf.baseurl to activate that codepath):
https://github.com/stefanozanella/createrepo/blob/master/createrepo/__init__.py#L553

**Comment by ntavares** [comment]
@nblair in fact, the XML from the primary is different than the one you've pasted (e.g. no closing tags on empty fields):
```
$ curl -s -o -  https://aquasecurity.github.io/trivy-repo/rpm/releases/8/x86_64/repodata/47e20126e2ea68d51adf0c7aaa2dc906fb6e322423cc3cad63ed71b7912a119b-primary.xml.gz  | gzip -d | grep location
  <location xml:base="https://github.com/aquasecurity/trivy/releases/download/" href="v0.48.0/trivy_0.48.0_Linux-64bit.rpm"/>
```
