### ISSUE TITLE
Migration 3.24 to 3.56

### ISSUE THREAD

**Issue by totalnooob** [sonatype/nexus-public#190]
Hello,

 

im getting issues when upgrading nexus repository 3.24 to 3.56. I've followed the manual https://support.sonatype.com/hc/en-us/articles/360010352014-Moving-a-Nexus-Repo-3-Installation-to-a-New-Location?_ga=2.106580355.182702858.1689246235-105440609.1686226349 copied all data files. But nexus wont start. log  https://pastebin.com/ivy5fxBC

 

When I tried running the same nexus version 3.24 new install with data from the old instance it worked. So there should be no problem with the database or data.

 

Thanks for help

**Comment by nblair** [comment]
Hi @totalnooob thanks for opening an issue. Two things to consider:

1. Did you stop the previous version of Nexus Repository before copying the data files? Always shut down your Nexus Repository instance before copying the database to make sure it is in a consistent state.
2. Have you tried upgrading to an intermediate version instead of going directly to the latest?
