### ISSUE TITLE
Unable to publish a new version 

### ISSUE THREAD

**Issue by IdanAdar** [sonatype/nexus-public#250]
We are facing the exact same issue as in https://issues.sonatype.org/browse/OSSRH-94988

```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project swagger-tools-maven-plugin: Remote staging failed: A message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and MIME media type text/html was not found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project swagger-tools-maven-plugin: Remote staging failed: A message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and MIME media type text/html was not found
```

The issue was closed by @jorlina seemingly as if everything is OK, but it does sound like there is an infrastructure issue in Sonatype. Because we are unable to login (password reset is not working in the Jira instance, too), we are unable to open a new ticket or even to manually publish instead via the Nexus UI.

**Comment by IdanAdar** [comment]
Any updates on the issue in sonatype that prevents proper publication, or why I can't reset my password? @jorlina

**Comment by jorlina** [comment]
@IdanAdar Can you provide more details on how the password reset isn't working for you?  This is the link you should be using https://issues.sonatype.org/secure/ForgotLoginDetails.jspa

As far as the ongoing issues with oss.sonatype.org you're facing, I can confirm that staging operations have become sluggish and plagued with timeouts over the past few days since [OSSRH-94988](https://issues.sonatype.org/browse/OSSRH-94988) was originally reported, but we have yet to determine root cause.

If you're coming under time pressure to release your artifacts, one thing I can offer is to migrate you to https://s01.oss.sonatype.org, but we will need an OSSRH issue to track that work.

**Comment by IdanAdar** [comment]
Yes, that's the one I am using - https://issues.sonatype.org/secure/ForgotLoginDetails.jspa
I'm not getting anything, not for my user email address nor for the automation user email address.

**Comment by jorlina** [comment]
We are indeed the administrators for issues.sonatype.org, and I'll have to do some digging to see if there's something going on with outbound emails.  In the meantime, we did run a few cleanup tasks and performed a service restart on oss.sonatype.org, so now might not be a bad time to try your release again to see if the performance is any better.

**Comment by IdanAdar** [comment]
Thanks, the cleanup and/or restart helped. We were able to publish. :)
