### ISSUE TITLE
Unable to find POMs for version 3.68.1-02

### ISSUE THREAD

**Issue by nesc58** [sonatype/nexus-public#395]
Hi,
there are missing packages for the version 3.68.1-02.
e.g. the mvnrepository does not show the version. Latest available version is 3.68.0-04:
https://mvnrepository.com/artifact/org.sonatype.nexus.plugins/nexus-plugins

Is there a release problem so the packages are not longer pushed anymore?

Thanks

**Comment by nblair** [comment]
Per the [release notes](https://help.sonatype.com/en/sonatype-nexus-repository-3-68-0-release-notes.html), 3.68.1-02 is an urgent bug fix that addresses [CVE-2024-4956](https://support.sonatype.com/hc/en-us/articles/29416509323923-CVE-2024-4956-Nexus-Repository-3-Path-Traversal-2024-05-16?_ga=2.204031065.896065347.1716210934-1336958315.1713905152).

We have intentionally suspended the sync of the EPL-licensed source code to this repository in order to provide time for Pro and OSS customers to adopt the latest release. This may delay attempts for an exploit to be developed.

We expect to restore the sync of the source code for that branch and future releases with next month's release. We apologize for the inconvenience.

**Comment by nesc58** [comment]
Thank you for the explanation and clarification.

I am asking because I want to update our nexus instance (we are using docker). But we need to compile some plugins that reference some of the not published packages.

Is it necessary to compile plugins against the deployed version e.g. now the 3.68.1-02 or can I compile the plugins against an older version e.g. 3.68.0-04 and everything should work? The plugins provides us some additional repository types.

Thanks

**Comment by nblair** [comment]
Yes, compiling against 3.68.0-04 is going to be API compatible and will work.

**Comment by nesc58** [comment]
Everything is working fine. Thank you for the answers
