### ISSUE TITLE
Migration from OrientDB to H2 fails

### ISSUE THREAD

**Issue by tobiasge** [sonatype/nexus-public#434]
While trying to migrate our Nexus installation to H2 in encountered the following error `Class 'SAML' was not found in database 'config'`
The full error log can be found here: https://gist.github.com/tobiasge/7f2f2f6bbecd5137c7ded40a74d6f257

What further information can I provide to help investigate this problem?

**Comment by mrprescott** [comment]
@tobiasge Can you clarify your edition? H2 is currently only supported for Pro instances, although we will change that shortly. If you're trying to make this change on a Nexus Pro instance, I recommend you have a registered support contact get in touch with our support.

**Comment by tobiasge** [comment]
It's an OSS edition.
I wanted to migrate away from OrientDB because I read that it won't be supported in the future.

**Comment by mrprescott** [comment]
@tobiasge Appreciate you being so proactive, and my apologies it wasn't clearer that you can't move _just yet_. We have some work to do so that this will work properly.

**Comment by xsnrg** [comment]
I am also a little concerned about this. The ability to update from 3.69 for OSS seems to be stopped until the DB migration is working, correct? I also do not see an issue to follow for this work. Did I miss one?

**Comment by mrprescott** [comment]
@xsnrg There are two meanings to 'database migration'. One is the built-in database structure migrations that run whenever you upgrade Repository. These work just fine.

@/tobiasge 's issue related to the external utility that migrates deployments from one database to another (e.g. OrientDB to OSS). This can't (yet) be used by OSS deployments, because OSS can only use OrientDB (for now). You'll see an announcement in our release notes when this changes.

**Comment by xsnrg** [comment]
@mrprescott Thank you for the clarification. My understanding is OrientDB is not supported beyond 3.69.0, and the migration to H2 from OrientDB does not yet exist for OSS, as you also stated. This means that anyone using OSS is locked at 3.69.0 as the migration for OSS's Orient DB to H2 is still being worked on. 

This is the issue I would like to follow if the ticket for the work exists. I would also like to know if I am misunderstanding something, of course.

**Comment by der-eismann** [comment]
We just hit the same issue and this is very confusing. While you can still upgrade to 3.70.0 on OSS with OrientDB, you cannot use Java 17 images or start the H2 migration yet. 

However in the `What's new` window on our Nexus instance it says
> **Embedded H2 Database**
> Nexus Repository is switching to an embedded H2 database as the default for new installations and small deployments.

so H2 is already available for non-Pro deployments? Also in [the migration docs](https://help.sonatype.com/en/migrating-to-a-new-database.html#migrating-from-orientdb-to-h2) it doesn't mention the Pro requirement anywhere apart from the PostgreSQL recommendation. 

But to be fair I just realized that in the [relase notes](https://help.sonatype.com/en/sonatype-nexus-repository-3-70-0-release-notes.html#orientdb--java-8--and-java-11-enter-extended-maintenance) it states clearly
> Release 3.71.0+ will require either an H2 or PostgreSQL database and Java 17.
> Note that both H2 and PostgreSQL are currently only available to Pro customers. We expect to announce a new database option for OSS customers and will provide detailed migration paths in our August 2024 release.

IMHO this whole OrientDB migration is communicated badly/inconsistently and done too hasty. 3.69 was the first release with Java 17 support (at least on Docker Hub) and in 3.71 there will only be Java 17 with no upgrade path yet for non-paying customers? Really curious what the *new database option for OSS customers* will look like.

**Comment by xsnrg** [comment]
> While you can still upgrade to 3.70.0 on OSS with OrientDB

Interesting. I was not able to find that this was an option anywhere, nor did anyone here reply that it was still an option. Either way, 3.71.0 would then be the break point so it really doesn't change much of the problem and the inconsistent documentation.

**Comment by lisadurant** [comment]
Hi everyone. We've just released a DB migrator to allow OSS deployments to move to H2. Please take a look at our [documentation specifically for migrating to 3.71.0+](https://help.sonatype.com/en/upgrading-to-nexus-repository-3-71-0-and-beyond.html)

You'll need to go to 3.70.1 first and use the 3.70.1 DB Migrator. Downloads for the 3.70.x line and the 3.70.x migrator are now in an [OrientDB-specific download page](https://help.sonatype.com/en/orientdb-downloads.html).

**Comment by majdi21** [comment]
I'm stuck at the migration step with an error. When I run the database migrator, I get a huge sequence of exception with the following root cause:

Caused by: java.util.jar.JarException: file:/path/to/nexus-db-migrator-3.70.1-03.jar has unsigned entries - META-INF/spring-configuration-metadata.json

I'm following these instructions: https://help.sonatype.com/en/migrating-to-a-new-database.html#migrating-from-orientdb-to-h2-162010

I'm not 100% sure I understand the instructions correctly so maybe I should state what I had done:

Step 1 in the instructions: Perform a full backup using normal backup procedures.
I created a backup using the "Admin - Export databases for backup" under tasks in nexus. Is this correct? I'm afraid I'm doing something wrong here and this is the root cause of my problem.

I basically ran that backup task, and then ran the migrator in the directory where the backup was created which resulted in the exception i mentioned above. Maybe this is not correct?

Thank you in advance!

**Comment by majdi21** [comment]
@lisadurant Any chance you have experienced this or have information about it? From searching online, it seems to be related to org.bouncycastle.jce.provider.BouncyCastleProvider ...

**Comment by lisadurant** [comment]
@majdi21 I have not heard of this specific issue; however, I do know we will be releasing a new 3.70.x and 3.70.x DB Migrator in the next few days to address a different issue. 

Your backup process looks correct: https://help.sonatype.com/en/configure-and-run-the-backup-task.html#configuring-the-backup-task-for-orientdb

I'm sorry I'm not more help; I'll let you know if I stumble onto any additional info, but I'm not seeing anything. Just to check - you're using OpenJDK, not Oracle JDK? That's the only thing I'm seeing as having caused similar errors in the past. The DB Migrator does require OpenJDK.

**Comment by BindewaldM** [comment]
On my side after migrating from orientDB to H2 the system information shows a system property called "h2.baseDir" which points to the directory where the H2 database is located.

**Comment by lisadurant** [comment]
@majdi21 I'm glad it worked!

Yes, the [System Requirements](https://help.sonatype.com/en/sonatype-nexus-repository-system-requirements.html#java-161935) state that Nexus Repository is tested on and supports OpenJDK, so that would be the recommendation.

You can determine your current database using the Data Store view; here's the [help docs](https://help.sonatype.com/en/configuring-nexus-repository-pro-for-h2-or-postgresql.html#data-store-configuration-view-to-determine-current-database) on that
