### ISSUE TITLE
missing nexus-repository-manager_3.70.001-2_all.deb

### ISSUE THREAD

**Issue by lunarfs** [sonatype/nexus-public#445]
I am missing .rpm and .deb packages for 3.70.1  in the public repo

the newest package in
https://repo.sonatype.com/#browse/browse:community-apt-hosted:packages
is
https://repo.sonatype.com/repository/community-apt-hosted/pool/n/nexus-repository-manager/nexus-repository-manager_3.69.002-2_all.deb

The .rpm packages of course has a different path, and i am not using that one, just realised that that one is also missing.

did you stop supplying .deb and .rpm packages? or was it just not created yet?

**Comment by bhamail** [comment]
@lunarfs The native installers your refer to are provided by "community" projects (in this case: [sonatype-nexus-community/nexus-repository-installer]([https://github.com/sonatype-nexus-community/nexus-repository-installer), and are not officially supported by the Nexus project.

That said, yes, those versions are missing, but only due to a glitch in the matrix. ;) There was a [problem](https://github.com/sonatype-nexus-community/nexus-repository-installer/issues/37) with the community build of the installer. Thanks to help from the community (Thanks @brandan-schmitz!), the build should be working again, and the next release should be happy.

**Comment by bhamail** [comment]
Well "happy" is a relative term. The build did at least succeed, however, the latest installers where not yet updated to require jdk 17 as a minimum. Therefore, you may run into a startup problem launching the application after the installer runs. I've since updated the installers "so the next build should be fine" (where have you heard that before?). 

A workaround that solved the above issue for me was to upgrade the default JDK manually on the host running the application to JDK 17. Then the daemon was able to successfully launch application.

**Comment by lunarfs** [comment]
Hi, 
Thanks for your fast response, and enlightening me on the process. I will make this fly on my Nexus OSS install with the given tools, however once people start upgrading to 3.71 I believe having the 3.70 package would be handy (As it is the package required on the upgrade path for Orient db to 3.71+) .
So i guess this case should be closed, as this first of all is the wrong project.. (I missed that one)
I will probably open the same issue in nexus-repository-installer as I believe having the .deb/.rpm packages will ease the process of upgrading to 3.71+.
Thanks again for your support, highly valued.

**Comment by bhamail** [comment]
@lunarfs Great point. In fact, I've run into exactly that issue of being somewhat wedged with an old OrientDB and a new NXRM 3.71 installed via the installer. "That dog won't hunt"(tm) as 3.71 requires H2 or PSQL. Be warned! Do the DB upgrade first!
