### ISSUE TITLE
Components Not Appearing in Browser After Migration to H2 from OrientDB

### ISSUE THREAD

**Issue by me-nilix** [sonatype/nexus-public#515]
Following the migration process, I have encountered an issue where components do not appear in the browser after loading. They only show up after a full index rebuild.

Steps Taken:
1. Updated Nexus OSS from version 3.52.0 to 3.70.3.
2. Created a backup of the database using a task.
3. Moved files to a separate directory.
4. Downloaded the required version of the migrator: nexus-db-migrator-3.70.3-01.jar.
5. Stopped Nexus using docker compose down.
6. Executed the command:
  
   java -Xmx16G -Xms16G -XX:+UseG1GC -XX:MaxDirectMemorySize=28672M -jar nexus-db-migrator-*.jar --migration_type=h2 --shutdown_compact=false
   
   The migration completed successfully.

7. Transferred the nexus.mv.db file to $data-dir/db.
8. Executed chown 200:200 $data-dir/db/nexus.mv.db.
9. Added nexus.datastore.enabled=true to $data-dir/etc/nexus.properties.
10. Modified docker-compose.yml from:
    
    - "INSTALL4J_ADD_VM_PARAMS=-Xms9G -Xmx9G -XX:+UseG1GC -XX:MaxDirectMemorySize=6717M -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    
    to:
    
    - "INSTALL4J_ADD_VM_PARAMS=-Xms14G -Xmx14G -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    
11. Started Nexus using docker compose up -d.

There were no errors in the logs. After a complete index rebuild, all packages appeared in the repositories, but when executing:
dotnet nuget push "$PACK_DIR/*.nupkg"

the package does not appear in the browser and cannot be found through search, although it is available for download.

The package only appears if I reindex the repository through a task. If I upload via the interface, the package shows up in search, but still does not display in the browser list until a full reindex of the repository is performed.

**Comment by alexander-vie** [comment]
We face similar issues with certain repos and Nexus OSS 3.74.0-05. We seem to find all assets via search and they are downloadable too, but certain hosted repos show up as empty when using browse (seen with raw, yum, apt, maven). Interestingly, the yum repo shows the yum index files but appears otherwise empty - reindexing of repo doesn't change anything.

**Comment by alexander-vie** [comment]
I was able fix our browsing issue using the hint from https://github.com/sonatype/nexus-public/issues/482#issuecomment-2444009459
In our case, creating and executing a job of type "Repair - Rebuild repository browse" was sufficient.

**Comment by obervinov** [comment]
Same problem.
The `Repair - Rebuild repository browse` task restored display for all repositories except `docker-proxy`. At the same time images are successfully retrieved via docker pull.
The problem seems to be in the elasticsearch indexes that store the data for building the asset tree in Browse.

**Comment by me-nilix** [comment]
The problem is solved. The solution came from https://github.com/sonatype/nexus-public/issues/515#issuecomment-2504159269

• Executed "Reconcile Component Database from Blob Store" for the nupkg repository

• Rebuilt Repository Browse

• Rebuilt Repository Search

After that, all repositories started working.
