### ISSUE TITLE
Vulnerability On the image docker pull sonatype/nexus3:3.75.1

### ISSUE THREAD

**Issue by venkatr25** [sonatype/nexus-public#537]
Hi Team,

We have 8 high vulnerability for the image : docker pull sonatype/nexus3:3.75.1  could you please help us to resolve this, attached the list of vulnerability scanned by twistlock 
[nexus_vulnerabiity.xlsx](https://github.com/user-attachments/files/18055395/nexus_vulnerabiity.xlsx)

Regards,
Venkat

**Comment by venkatr25** [comment]
Any update on this please

**Comment by mrprescott** [comment]
@venkatr25, thanks for reporting these security findings. We are already aware of most dependency vulnerabilities because of our continuous monitoring with Nexus Lifecycle.

We consider all dependency vulnerabilities to be potentially exploitable, and we have already queued them for remediation.

Sonatype follows a responsible disclosure process for any confirmed vulnerabilities. For the safety of our customers and users, we don’t disclose exploitability of scan findings until after upgraded versions of Nexus Repository are made available.

For more information on our processes, please see [Repository Security Vulnerabilities](https://help.sonatype.com/repomanager3/product-information/repository-security-vulnerabilities).

You can subscribe to announcements of new releases and fixes for verified exploitable vulnerabilities via the [Nexus Repository Pro announcements Google group](https://groups.google.com/a/glists.sonatype.com/g/nexus-pro-announcements).

**Comment by venkatr25** [comment]
Thanks for you update @mrprescott 

On next release all the vulnerability will be remediate ?

**Comment by venkatr25** [comment]
Hi @mrprescott 

We have tried with the latest image "docker pull sonatype/nexus3:3.76.0"  

but still have High vulnerability scanned by twist lock please find the attached report, requesting you to fix all this vulnerability on the fix pack release 

[nexus_scan_report.xlsx](https://github.com/user-attachments/files/18345950/nexus_scan_report.xlsx)


Regards,
Venkat
